### ISSUE TITLE
keep saying token is incorrect

### ISSUE THREAD

**Issue by sumnermcclure4554554** [MindfulMinun/discord-haruka#14]
# Bug report

### What’s the problem?
A detailed description of the behavior. (i.e., Haruka is doing _this_ instead of _that_.)

### What did you expect? What actually happened?
- The output you expected. (I expected 2 + 2 to be 4.)
- The output you got. (2 + 2 was instead Fish.)

### How to reproduce?
1. Steps on reproducing the bug. (e.g., type _this_ followed by _that_.)

### Additional notes
Too much information is better than too little. Screenshots are more than welcome.

**Comment by MindfulMinun** [comment]
Firstly, thanks for checking out this Discord bot, it means a lot. Unfortunately I'm going to need some more information regarding the error in order for this issue to be actionable. It would mean the world if you filled out the template above.

Haruka could throw an error like that for any number of reasons. Please double-check that you fulfilled the steps outlined in [the installation portion of the README](https://github.com/MindfulMinun/discord-haruka#installation).
- Does this error get thrown immediately on startup or only when using a specific command in Discord?
- Did you remember to rename `.env.ex` to `.env`?
- Did you surround your equal signs with spaces in your `.env` file? (There shouldn't be any.)
- Are all of your tokens defined? (They don't have to be. The only required one is `DISCORD_TOKEN`, but you may also want to define `HARUKA_OPS`.)
    - Did you prefix any unwanted functions that require a token with an underscore so they're ignored by Haruka?

Any and all information you could give me would be great. If GitHub seems a bit difficult to manage you could always message me privately on Discord (MindfulMinun#3386) if you're not used to the GitHub workflow. However, **please do not send your `.env` file** to me or to anyone, since it contains keys you should keep private.

**Comment by MindfulMinun** [comment]
Since there isn't enough info on this issue to be actionable, and since there hasn't been a response in two weeks, I'm going to go ahead and close this issue. But please don't let that stop you from messaging me with more info on this issue. My Discord tag is MindfulMinun#3386 and I'm more than willing to help!
